# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example-watchOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  platform :ios, '9.0'
  use_frameworks!

  # Pods for Example-watchOS
  pod 'SensorsAnalyticsSDK', :path=>'../../SensorsAnalyticsSDK.podspec'

end

target 'Example-watchOS Watch App' do
  # Comment the next line if you don't want to use dynamic frameworks
  platform :watchos, '7.0'
  use_frameworks!

  # Pods for Example-watchOS Watch App
 pod 'SensorsAnalyticsSDK', :path=>'../../SensorsAnalyticsSDK.podspec'
end
