# Uncomment the next line to define a global platform for your project
 platform :osx, '10.13'

target 'example-macOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for example-macOS
  pod 'SensorsAnalyticsSDK', :path=>'../../SensorsAnalyticsSDK.podspec'

end
